<?php
/**
 * Site audit screen.
 *
 * @package WPCustomSeo
 *
 * @var string                  $action       Admin-post action for refreshing.
 * @var array<string, mixed>    $report       Cached report.
 * @var array<string, string>   $levels       Level labels.
 * @var array<string, string>   $descriptions Level descriptions.
 * @var string[]                $remedies     Cannibalization remedies.
 * @var bool                    $refreshed    Whether the report was just rebuilt.
 */

use WPCustomSeo\Audit\Finding;

defined( 'ABSPATH' ) || exit;

?>
<div class="wrap wpcseo-wrap">
	<h1><?php esc_html_e( 'Site Audit', 'wp-custom-seo' ); ?></h1>

	<?php if ( $refreshed ) : ?>
		<div class="notice notice-success is-dismissible"><p><?php esc_html_e( 'Audit rebuilt.', 'wp-custom-seo' ); ?></p></div>
	<?php endif; ?>

	<p class="wpcseo-lede">
		<?php esc_html_e( 'Every figure here is counted from your own content, not estimated and not generated by a model. Nothing is sent anywhere, no URLs are requested, and running it costs nothing.', 'wp-custom-seo' ); ?>
	</p>

	<div class="wpcseo-grid">
		<?php foreach ( $levels as $wpcseo_level => $wpcseo_label ) : ?>
			<section class="wpcseo-card">
				<h2><?php echo esc_html( $wpcseo_label ); ?></h2>
				<p class="wpcseo-score is-<?php echo esc_attr( Finding::GOOD === $wpcseo_level ? 'good' : ( Finding::CRITICAL === $wpcseo_level ? 'bad' : 'warn' ) ); ?>">
					<?php echo esc_html( number_format_i18n( (int) ( $report['totals'][ $wpcseo_level ] ?? 0 ) ) ); ?>
				</p>
				<p class="description"><?php echo esc_html( $descriptions[ $wpcseo_level ] ); ?></p>
			</section>
		<?php endforeach; ?>
	</div>

	<p>
		<?php
		printf(
			/* translators: %s: date and time. */
			esc_html__( 'Generated %s. The report is cached for an hour.', 'wp-custom-seo' ),
			esc_html( (string) mysql2date( get_option( 'date_format' ) . ' ' . get_option( 'time_format' ), (string) $report['generated'] ) )
		);
		?>
	</p>

	<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>">
		<input type="hidden" name="action" value="<?php echo esc_attr( $action ); ?>">
		<?php wp_nonce_field( $action ); ?>
		<?php submit_button( __( 'Run the audit again', 'wp-custom-seo' ), 'secondary', 'submit', false ); ?>
	</form>

	<?php if ( ! $report['findings'] ) : ?>
		<?php
		$wpcseo_empty = \WPCustomSeo\Admin\UI::empty_state(
			'shield',
			__( 'Nothing to report', 'wp-custom-seo' ),
			__( 'Every check the audit runs came back clean. Findings appear here as content is published and the site grows.', 'wp-custom-seo' )
		);

		// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- UI::empty_state() escapes every argument it is given and returns finished markup.
		echo $wpcseo_empty;
		?>
	<?php endif; ?>

	<?php foreach ( $report['findings'] as $wpcseo_finding ) : ?>
		<section class="wpcseo-finding is-<?php echo esc_attr( $wpcseo_finding->level ); ?>">
			<h2>
				<span class="wpcseo-badge <?php echo esc_attr( Finding::GOOD === $wpcseo_finding->level ? 'is-on' : 'is-off' ); ?>">
					<?php echo esc_html( $levels[ $wpcseo_finding->level ] ); ?>
				</span>
				<?php echo esc_html( $wpcseo_finding->title ); ?>
			</h2>

			<p><strong><?php esc_html_e( 'Why it matters', 'wp-custom-seo' ); ?></strong> — <?php echo esc_html( $wpcseo_finding->why ); ?></p>
			<p><strong><?php esc_html_e( 'What to do', 'wp-custom-seo' ); ?></strong> — <?php echo esc_html( $wpcseo_finding->action ); ?></p>

			<?php if ( 'cannibalization' === $wpcseo_finding->id ) : ?>
				<ul class="wpcseo-ai-list">
					<?php foreach ( $remedies as $wpcseo_remedy ) : ?>
						<li><?php echo esc_html( $wpcseo_remedy ); ?></li>
					<?php endforeach; ?>
				</ul>
			<?php endif; ?>

			<?php if ( $wpcseo_finding->items ) : ?>
				<details>
					<summary><?php esc_html_e( 'Evidence', 'wp-custom-seo' ); ?></summary>
					<?php if ( 'cannibalization' === $wpcseo_finding->id ) : ?>
						<?php foreach ( $wpcseo_finding->items as $wpcseo_clash ) : ?>
							<p>
								<code><?php echo esc_html( $wpcseo_clash['signature'] ); ?></code>
							</p>
							<ul class="wpcseo-ai-list">
								<?php foreach ( $wpcseo_clash['posts'] as $wpcseo_post ) : ?>
									<li>
										<a href="<?php echo esc_url( (string) get_edit_post_link( (int) $wpcseo_post['id'] ) ); ?>">
											<?php echo esc_html( $wpcseo_post['title'] ); ?>
										</a>
										— <?php echo esc_html( $wpcseo_post['keyword'] ); ?>
									</li>
								<?php endforeach; ?>
							</ul>
						<?php endforeach; ?>
					<?php else : ?>
						<table class="wp-list-table widefat striped wpcseo-ai-table">
							<tbody>
								<?php foreach ( $wpcseo_finding->items as $wpcseo_item ) : ?>
									<tr>
										<?php foreach ( (array) $wpcseo_item as $wpcseo_key => $wpcseo_value ) : ?>
											<?php if ( is_scalar( $wpcseo_value ) ) : ?>
												<td>
													<?php if ( 'post_title' === $wpcseo_key && isset( $wpcseo_item['ID'] ) ) : ?>
														<a href="<?php echo esc_url( (string) get_edit_post_link( (int) $wpcseo_item['ID'] ) ); ?>">
															<?php echo esc_html( (string) $wpcseo_value ); ?>
														</a>
													<?php elseif ( 'title' === $wpcseo_key && isset( $wpcseo_item['id'] ) ) : ?>
														<a href="<?php echo esc_url( (string) get_edit_post_link( (int) $wpcseo_item['id'] ) ); ?>">
															<?php echo esc_html( (string) $wpcseo_value ); ?>
														</a>
													<?php else : ?>
														<?php echo esc_html( (string) $wpcseo_value ); ?>
													<?php endif; ?>
												</td>
											<?php endif; ?>
										<?php endforeach; ?>
									</tr>
								<?php endforeach; ?>
							</tbody>
						</table>
					<?php endif; ?>

					<?php if ( $wpcseo_finding->count > count( $wpcseo_finding->items ) ) : ?>
						<p class="description">
							<?php
							printf(
								/* translators: 1: shown, 2: total. */
								esc_html__( 'Showing %1$d of %2$d.', 'wp-custom-seo' ),
								count( $wpcseo_finding->items ),
								(int) $wpcseo_finding->count
							);
							?>
						</p>
					<?php endif; ?>
				</details>
			<?php endif; ?>

			<?php if ( '' !== $wpcseo_finding->link ) : ?>
				<p><a class="button" href="<?php echo esc_url( $wpcseo_finding->link ); ?>"><?php esc_html_e( 'Go and fix this', 'wp-custom-seo' ); ?></a></p>
			<?php endif; ?>
		</section>
	<?php endforeach; ?>
</div>
